name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites on Ubuntu
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            python3 \
            python3-pip
          pip install pytest pytest-cov

      - name: Build rtype binaries on Ubuntu (desktop)
        run: make re

      - name: Check Ubuntu build (desktop)
        run: |
          test -f 304pacman

      # - name: Test project
      #   run: make tests_run
