##
## EPITECH PROJECT, 2020
## makefile
## File description:
## desc
##

SRC		=		$(shell find -type f -name "*.c")

NAME	=		libmy.a

OBJ		=		$(SRC:.c=.o)

CFLAGS  =		-Wall -Wshadow -Wextra

all:	$(NAME)

$(NAME):	$(OBJ)
	ar rc $(NAME) $(OBJ)

clean:
	rm -rf $(OBJ)

fclean:		clean
	rm -rf $(NAME)

re: fclean all
