
  - name: "Install ACL packages"
    become: yes
    apt:
      name: "acl"
      state: present
      update_cache: yes

  - name: "Install PostgreSQL packages"
    become: yes
    apt:
      name: "postgresql-12"
      state: present
      update_cache: yes

  - name: Download pip installer
    become: yes
    get_url:
      url: https://bootstrap.pypa.io/get-pip.py
      dest: /tmp/get-pip.py

  - name: Install pip
    become: yes
    shell: /usr/bin/python3 /tmp/get-pip.py

  - name: Install python-postgres packages
    become: yes
    pip: "name=psycopg2-binary state=present"

  - name: "Check if PostgreSQL is initialized"
    ansible.builtin.stat:
      path: "../files/pg_hba.conf"
    register: postgres_data

  - name: "Start and enable services"
    service:
      name: postgresql
      state: started
      enabled: yes

  - name: "Create database"
    postgresql_db:
      state: present
      name: "{{ db_name }}"
    become: yes
    become_user: postgres

  - name: "Create db user"
    postgresql_user:
      state: present
      name: "{{ db_user }}"
      password: "{{ db_password }}"
    become: yes
    become_user: postgres

  - name: "Grant db user access to db"
    postgresql_privs:
      type: database
      database: "{{ db_name }}"
      roles: "{{ db_user }}"
      grant_option: no
      privs: all
    become: yes
    become_user: postgres
